### ISSUE TITLE
Make expire enum (add fully manual mode)

### ISSUE THREAD

**Issue by rominf** [coleifer/ucache#1]
It would be nice to have an option to disable both DB and `ucache` expiry mechanisms. I need it because expiry by timeout doesn't suit my library (https://github.com/rominf/profanity-filter). I wish to handle expiry from the library code.

So I propose to make an enum:
```python
UC_EXPIRE_OFF = 0
UC_EXPIRE_MANUAL = 1
UC_EXPIRE_AUTO = 2
```

**Comment by coleifer** [comment]
ucache uses a "manual" approach only for storage engines that do not support automatic expiry.

Also, you can disable caching behavior using `debug=True` when initializing.

**Comment by rominf** [comment]
> ucache uses a "manual" approach only for storage engines that do not support automatic expiry.

Ok. So to say in other words, I want to disable DB _or_ `ucache` expiry mechanisms. Now for disabling DB (say, Redis) expiry mechanism I can do nothing, and for disabling `ucache` (say, for `MemoryStorage`) expiry mechanism, I should do `manual_expire = False`. The first is unfortunate, the second is unlogical.

> Also, you can disable caching behavior using debug=True when initializing.

This will make the whole `ucache` library useless. I want to cache, I just want to manage the expiry myself.

So, speaking of enum, for storage engines that do not support automatic expiry, `expire_type` will be set to `UC_EXPIRE_MANUAL`, for those, who do - `UC_EXPIRE_AUTO`, but user can change those values to `UC_EXPIRE_OFF` and then `ucache` "manual" approach will stop working, and for storage that support automatic expiry, `timeout` will not be specified (for example, for Redis, `ucache` will call `set` instead of `setex`).

Is it clearer now?

**Comment by coleifer** [comment]
ucache presents the same interface whether you are using something like Redis / KyotoTycoon (which has automatic expiry) or something like sqlite3 which requires manual expiration.

> This will make the whole ucache library useless. I want to cache, I just want to manage the expiry myself.

Yes, it disables all caching. I couldn't understand why you would want to use this library if you do not want to use the caching behavior. Just use a Redis client or whatever. Or just set the timeout very high.

> Is it clearer now?

No. The very fact that it is complicated, has different meaning for different storages, etc., should be an obvious sign that it's a shit idea.

**Comment by rominf** [comment]
There are different ways of managing cache invalidation, and setting TTL is just one of those. This StackOverflow answer: https://stackoverflow.com/a/1743762/2108548 describes two ways (the first one is to use TTL, the second is similar to what I want to use).
Also, there is LRU cache which also doesn't require TTL.

**Comment by coleifer** [comment]
I'm well aware that there are many ways to implement a cache. This library doesn't implement eviction strategies.

**Comment by rominf** [comment]
I'm not asking for implementing of concrete strategy. I'm asking to let the programmer solve it himself by writing code externally (in his program/library). Sure, now the programmer can specify `timeout = 2147483647` (at least for Redis). This is practically equal to not using TTL. But max value could differ between backends. Also, for backends, that do not support TTL, this means that `ucache` will check the condition which is always `True`. Of course, this is fast, but not very beautiful.

Ok, so do I understand you correctly, that you won't accept the patch that makes `ucache` work without TTL even if I prepare it myself?
